version: 2.0
jobs:
  build_docs:
    docker:
      - image: asciidoctor/docker-asciidoctor
    working_directory: /documents/
    steps:
      - checkout
      - run: mkdir -p output
      - run: asciidoctor -r asciidoctor-diagram -D /documents/output *.adoc
      - run: mv output/README.html output/index.html
      - save_cache:
          key: v1-docs-output-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /documents/output
            - /documents/.circleci/deploy.sh
  deploy_github_pages:
    docker:
      - image: bravissimolabs/alpine-git
    working_directory: /documents/
    steps:
      - restore_cache:
          key: v1-docs-output-{{ .Environment.CIRCLE_SHA1 }}
      - deploy:  /documents/.circleci/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_docs:
          filters:
            branches:
              only: master
              ignore: gh-pages
      - deploy_github_pages:
          requires:
            - build_docs
          filters:
            branches:
              only: master
              ignore: gh-pages
